# File generated by PostSharp.Engineering 2023.2.304, method DependenciesConfigurationFile.TryWrite.

# C:\Users\GaelFraiteur\.build-artifacts\PostSharpPackage\PostSharpGitHub_PostSharp20260_BuildDistribution\313071\artifacts\publish\private\PostSharpPackage.version.props
$VolumeMappings += "C:\Users\GaelFraiteur\.build-artifacts\PostSharpPackage\PostSharpGitHub_PostSharp20260_BuildDistribution\313071\artifacts\publish\private:C:\Users\GaelFraiteur\.build-artifacts\PostSharpPackage\PostSharpGitHub_PostSharp20260_BuildDistribution\313071\artifacts\publish\private:ro"
$MountPoints += "C:\Users\GaelFraiteur\.build-artifacts\PostSharpPackage\PostSharpGitHub_PostSharp20260_BuildDistribution\313071\artifacts\publish\private"

